Models/ErrorViewModel.cs
using System;

namespace GraniteHouse.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProductTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GraniteHouse.Models
{
    public class ProductTypes
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
    }
}

Models/SpecialTags.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Granitehouse.Models 
{
    class SpecialTags 
    {
      public string Id { get; set; }
        
      [Required]  
      public string Name { get; set; }
    }
}

Models/TagTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Granitehouse.Models 
{
    class TagTypes 
    {
      public string Name { get; set; }
    }
}

Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GraniteHouse.Models;

namespace GraniteHouse.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Models;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class ProductTypesController : Controller
    {

        private readonly ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }


        // GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        // POST Create Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if(ModelState.IsValid)
            {
                _db.Add(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }







        // GET Edit Action Method
        public async Task<IActionResult> Edit(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var productType = await _db.ProductTypes.FindAsync(id);
            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }

        // POST Edit Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductTypes productTypes)
        {
            if(id!=productTypes.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }





        // GET Details Action Method
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = await _db.ProductTypes.FindAsync(id);
            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }












        // GET Delete Action Method
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = await _db.ProductTypes.FindAsync(id);
            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }

        // POST Delete Action Method
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productTypes = await _db.ProductTypes.FindAsync(id);
            _db.ProductTypes.Remove(productTypes);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }










    }
}

Controllers/SpecialTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Models;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
            private readonly ApplicationDbContext _db;
            public SpecialTagsController(ApplicationDbContext db)
            {
                _db = db;
            }
            
            public IActionResult Index()
            {
                return View(_db.SpecialTags.ToList());
            }
            
            // GET Create Action Method
            public IActionResult Create()
            {
                return View();
            }
            
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(SpecialTags specialTags)
            {
                If(ModelState.IsValid)
                {
                    _db.Add(specialTags);
                    await _db.SaveChangesAsnc();
                    return RedirectToAction(Nameof(Index));
                }
                return View(specialTags);
            }
            
            
            // GET Action Method Edit
            public async Task<IActionResult> Edit(int? id)
            {
                if(id==null)
                {
                    return NotFound();
                }
                
                var specialTag = await _db.SpecialTags.FindAsync(Id);
                if(specialTag == null)
                {
                    return NotFound();
                }
                
                return View(specialTag);
                
            }
            
            
            
            
            
            
            
            
            
            
            // POST Edit Action Method
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, SpecialTags specialTags)
            {
                if(!id == specialTags.Id)
                {
                    return NotFound();
                }
                
                if(ModelState.IsValid)
                {
                    _db.Update(specialTags);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
                return View(specialTags);
                
            }
            
            
    }

}

Areas/Admin/Views/ProductTypes/Create.cshtml
@model GraniteHouse.Models.ProductTypes


@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>
<form method="post" asp-action="Create">
    <div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <input type="submit" value="Create" />
    <a asp-action="Index">Back to list</a>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/ProductTypes/Delete.cshtml
@model GraniteHouse.Models.ProductTypes


@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>
<form method="post" asp-action="Delete">
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" disabled />
    </div>

    <input type="submit" asp-route-id="@Model.Id" value="Delete" />
    <a asp-action="Index">Back to list</a>
</form>

Areas/Admin/Views/ProductTypes/Details.cshtml
@model GraniteHouse.Models.ProductTypes


@{
    ViewData["Title"] = "Details";
}

<h2>details</h2>
<div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <label asp-for="Name"></label><br />
    <input asp-for="Name" disabled />
</div>

<a asp-action="Edit" asp-route-id="@Model.Id">edit</a>


<a asp-action="Index">Back to list</a>


Areas/Admin/Views/ProductTypes/Edit.cshtml
@model GraniteHouse.Models.ProductTypes


@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<form method="post" asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <input type="submit" asp-route-id="@Model.Id" value="Update" />
    <a asp-action="Index">Back to list</a>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/ProductTypes/Index.cshtml

@model IEnumerable<GraniteHouse.Models.ProductTypes>



@{
    ViewData["Title"] = "Index";
}

<br />
<br />

<div class="row">
    <div class="col-6">
        <h2 class="text-info">Product Type List</h2>

        <div class="col-6 text-right">
            <a asp-action="Create" class="btn btn-info">&nbsp; New Product type</a>
        </div>
    </div>
</div>

<div>
    <table class="table table-striped">
        <tr class="table-info">
            <th>
                @Html.DisplayNameFor(m => m.Name)
            </th>
            <th></th>
        </tr>

        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.Name)
                </td>
                <td>

                    <partial name="_TableButtonPartial" model="item.Id" />

                </td>
            </tr>
        }
    </table>
</div>

Areas/Customer/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Areas/Customer/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GraniteHouse</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top" >
        <a class="navbar-brand" href="#">Granite house</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                


                <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a></li>





            </ul>

        </div>
        <div><partial name="_LoginPartial" /></div>
    </nav>








































    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - GraniteHouse</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@model int 


@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<td style="width: 150px;">
    <a type="button" href="@Url.Action("Edit/"+Model)">Edit</a>
   
    <a type="button" href="@Url.Action("Details/"+Model)">Details</a>

    <a type="button" href="@Url.Action("Delete/"+Model)">Delete</a>

</td>